name: Deploy Inotebook
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin 
    #   - run: docker build -t lavpreet/react-test -f ./client/Dockerfile.dev ./client
    #   - run: docker run -e CI=true lavpreet/react-test npm test

      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/inotebook-client ./inotebook
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/inotebook-nginx ./nginx
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/inotebook-server ./Django-backend/iNotebookBackend
    #   - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-worker ./worker

      - run: docker push ${{ secrets.DOCKER_USERNAME }}/inotebook-client
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/inotebook-nginx
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/inotebook-server
    #   - run: docker push ${{ secrets.DOCKER_USERNAME }}/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: inotebook-app
          environment_name: Inotebook-env
          existing_bucket_name: elasticbeanstalk-ap-south-1-333640615095
          region: ap-south-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip